#!/bin/sh

# psql can't check for a file's existence, so we'll provide an empty local
# file that users can override with their custom dotfiles. To set your own
# personal settings, place your own file in ~/.psqlrc.local

touch "$HOME"/.psqlrc.local

# we do not want vim
# if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
  # vim -E -s +PlugUpgrade +qa
# else
  # curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      # https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
# fi
# vim -u "$HOME"/.vimrc.bundles +PlugUpdate +PlugClean! +qa

reset -Q

# detect old OS X broken /etc/zshenv and suggest rename
if grep -qw path_helper /etc/zshenv 2>/dev/null; then
  dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)

cat <<MSG >&2
Warning: \`/etc/zshenv' configuration file on your system may cause unexpected
PATH changes on subsequent invocations of the zsh shell. The solution is to
rename the file to \`zprofile':
  sudo mv /etc/{zshenv,zprofile}

(called from ${dir}/post-up:${LINENO})

MSG
fi
